#include <Audio.h>
#include "vfx.h" // Make sure this matches the class name generated by Faust

AudioInputI2S in;
AudioOutputI2S out;
AudioControlSGTL5000 audioShield;

// Assuming "vfx" is the class name generated by Faust
vfx vfx;

// Modify these connections to route through the vfx
AudioConnection* patchCords[3];

void setup() {
  Serial.begin(9600);
  AudioMemory(6);
  audioShield.enable();
  audioShield.inputSelect(AUDIO_INPUT_MIC);
  audioShield.micGain(10); // in dB
  audioShield.volume(1);

  // Initialize vfx if necessary
  // vfx.init();

  // Setup audio connections
  patchCords[0] = new AudioConnection(in, 0, vfx, 0);
  patchCords[1] = new AudioConnection(vfx, 0, out, 0);
  patchCords[2] = new AudioConnection(vfx, 0, out, 1);
}

void loop() {
  int sensorValue_0 = analogRead(A0);
  float room_size = sensorValue_0/1023;
  vfx.setParamValue("fHslider1", room_size);

  int sensorValue_1 = analogRead(A1);
  float pitch = sensorValue_1/51.15 - 9;
  vfx.setParamValue("fHslider2", pitch);

  /*
  int sensorValue_2 = analogRead(A2);
  float gain = sensorValue_2/1023;
  vfx.setParamValue("Gain", gain);
  */

  // Here, you can add code to adjust vfx parameters in real-time if needed
}
