#include <Audio.h>
#include "vocoder.h" // Make sure this matches the class name generated by Faust

AudioInputI2S in;
AudioOutputI2S out;
AudioControlSGTL5000 audioShield;

// Assuming "Vocoder" is the class name generated by Faust
vocoder vocoder;

// Modify these connections to route through the vocoder
AudioConnection* patchCords[3];

void setup() {
  Serial.begin(9600);
  AudioMemory(6);
  audioShield.enable();
  audioShield.inputSelect(AUDIO_INPUT_MIC);
  audioShield.micGain(10); // in dB
  audioShield.volume(1);

  // Initialize vocoder if necessary
  // myVocoder.init();

  // Setup audio connections
  patchCords[0] = new AudioConnection(in, 0, vocoder, 0);
  patchCords[1] = new AudioConnection(vocoder, 0, out, 0);
  patchCords[2] = new AudioConnection(vocoder, 0, out, 1);
}

void loop() {
  int sensorValue = analogRead(A0);
  float freq = sensorValue + 10;
  Serial.println(freq);
  vocoder.setParamValue("Gain", 1);
  
  vocoder.setParamValue("Frequency", freq);
  // Here, you can add code to adjust vocoder parameters in real-time if needed
}
